import type { CompanyCheckDictionary } from "./types"

export const companyCheckEn: CompanyCheckDictionary = {
  metaTitle: "Check an employer: headcount, activity, gender pay index, carbon report",
  metaDescription:
    "Before you apply, check a French company by name or SIREN: headcount, activity, gender equality index, social economy, mission-driven status, carbon report. Free, from French government open data.",
  eyebrow: "Free tool",
  title: "Check an employer before you apply",
  subtitle:
    "Its headcount, its activity and its commitments: gender equality, social and solidarity economy, mission-driven company, carbon report.",
  form: {
    label: "Company name or SIREN",
    hint: "At least 3 characters, or the 9 digits of the SIREN (a SIRET works too).",
    placeholder: "E.g. Helpline, 381 983 568…",
    submit: "Search",
    submitting: "Searching…",
    privacyNote:
      "No account, no personal data: only your search is sent to the French company directory.",
  },
  results: {
    title: "{count} matching companies",
    noMatch:
      "No company matches “{query}”. Check the spelling, or enter its SIREN (9 digits).",
    closed: "Closed",
    back: "Back to the results",
  },
  unknown: {
    title: "Company not found",
    body: "The French company directory does not know this SIREN, or the company asked for its data not to be published.",
  },
  sheet: {
    siren: "SIREN {siren}",
    closed: "This company is registered as closed.",
    figuresTitle: "Key figures",
    headcount: "Headcount",
    activity: "Activity",
    created: "Founded",
    establishments: "Open establishments",
    revenue: "Revenue {year}",
    missing: "Not published",
    categories: {
      PME: "Small or medium-sized company",
      ETI: "Mid-sized company",
      GE: "Large company",
    },
    nafSections: {
      A: "Agriculture, forestry and fishing",
      B: "Mining and quarrying",
      C: "Manufacturing",
      D: "Energy",
      E: "Water, waste and remediation",
      F: "Construction",
      G: "Wholesale and retail trade",
      H: "Transport and storage",
      I: "Accommodation and food",
      J: "Information and communication",
      K: "Finance and insurance",
      L: "Real estate",
      M: "Professional, scientific and technical activities",
      N: "Administrative and support services",
      O: "Public administration",
      P: "Education",
      Q: "Health and social work",
      R: "Arts, entertainment and recreation",
      S: "Other services",
      T: "Households as employers",
      U: "Extraterritorial organisations",
    },
    commitmentsTitle: "Commitments",
    commitments: {
      mission: "Mission-driven company (société à mission)",
      ess: "Social and solidarity economy",
      inclusive: "Inclusive employer",
      ges: "Carbon report published",
      egapro: "Gender equality index",
    },
    yes: "Yes",
    no: "No",
    egaproScore: "{score}/100 in {year}",
    egaproMissing: "Not declared",
    employerPageTitle: "France Travail employer page",
    employerPageLink: "See its employer page",
    employerPageOffers: "{count} published offers",
    employerPageMissing: "No known employer page for this company.",
    newTab: "(new tab)",
    sourcesTitle: "Sources",
    sources: {
      annuaire: "Annuaire des entreprises (French government company directory)",
      egapro: "Gender equality index: French Ministry of Labour (Egapro)",
      employerPage: "Employer page: France Travail",
    },
    again: "Check another employer",
  },
  page: {
    breadcrumbLabel: "Breadcrumb",
    title: "{name}: employer profile",
    metaTitle: "{name}: headcount, activity, gender pay index, commitments",
    metaDescription:
      "{name}, SIREN {siren}. {summary} Gender equality index, commitments and public sources, before you apply.",
    summaryActivity: "Sector: {sector} (NAF {naf}).",
    summaryHeadcount: "Headcount: {headcount}.",
    summaryCreated: "Founded in {year}.",
    sheetTitle: "The company's record",
    hiringTitle: "Where it hires",
    hiringItem: "{job}, {city} ({department})",
    hiringSource:
      "Hiring establishments: La Bonne Boîte (France Travail). A link leads to the job's figures in the department when we have them.",
    sameSectorTitle: "Other employers in the same sector",
    refreshed: "Data read on {date}.",
    toolLink: "Check another employer",
  },
  cta: {
    title: "What about the companies hiring in your field?",
    body: "Those hiring near you, even without a job ad, each with its record. Create your account: all it takes is an email.",
    button: "See the companies that are hiring",
  },
  lead: {
    body: "We'll send you a sign-in link: it opens the list of companies that are hiring.",
    emailLabel: "Your email",
    emailPlaceholder: "you@example.com",
    consent: "I agree to create a CVSpark account and receive this sign-in link.",
    submit: "Get my link",
    submitting: "Sending…",
    success: "Check your inbox",
    successBody: "The link opens the list of companies that are hiring.",
  },
}
