import type { CompanyCheckDictionary } from "./types"

export const companyCheckFr: CompanyCheckDictionary = {
  metaTitle: "Vérifier un employeur : effectif, activité, égalité F/H, bilan carbone",
  metaDescription:
    "Avant de postuler, vérifiez une entreprise par son nom ou son SIREN : effectif, activité, index égalité femmes-hommes, ESS, société à mission, bilan carbone. Gratuit, d'après les données publiques de l'État.",
  eyebrow: "Outil gratuit",
  title: "Vérifiez un employeur avant de postuler",
  subtitle:
    "Son effectif, son activité et ses engagements : égalité femmes-hommes, économie sociale et solidaire, société à mission, bilan carbone.",
  form: {
    label: "Nom de l'entreprise ou SIREN",
    hint: "3 caractères au moins, ou les 9 chiffres du SIREN (un SIRET marche aussi).",
    placeholder: "Ex. : Helpline, 381 983 568…",
    submit: "Rechercher",
    submitting: "Recherche…",
    privacyNote:
      "Aucun compte, aucune donnée personnelle : seule votre recherche est envoyée à l'Annuaire des entreprises.",
  },
  results: {
    title: "{count} entreprises correspondent",
    noMatch:
      "Aucune entreprise ne correspond à « {query} ». Vérifiez l'orthographe, ou saisissez son SIREN (9 chiffres).",
    closed: "Fermée",
    back: "Retour aux résultats",
  },
  unknown: {
    title: "Entreprise introuvable",
    body: "L'Annuaire des entreprises ne connaît pas ce SIREN, ou l'entreprise a demandé que ses données ne soient pas diffusées.",
  },
  sheet: {
    siren: "SIREN {siren}",
    closed: "Cette entreprise est déclarée fermée.",
    figuresTitle: "Chiffres clés",
    headcount: "Effectif",
    activity: "Activité",
    created: "Création",
    establishments: "Établissements ouverts",
    revenue: "Chiffre d'affaires {year}",
    missing: "Non publié",
    categories: {
      PME: "Petite ou moyenne entreprise",
      ETI: "Entreprise de taille intermédiaire",
      GE: "Grande entreprise",
    },
    nafSections: {
      A: "Agriculture, sylviculture et pêche",
      B: "Industries extractives",
      C: "Industrie manufacturière",
      D: "Énergie",
      E: "Eau, déchets et dépollution",
      F: "Construction",
      G: "Commerce, réparation d'automobiles",
      H: "Transports et entreposage",
      I: "Hébergement et restauration",
      J: "Information et communication",
      K: "Finance et assurance",
      L: "Immobilier",
      M: "Activités spécialisées, scientifiques et techniques",
      N: "Services administratifs et de soutien",
      O: "Administration publique",
      P: "Enseignement",
      Q: "Santé humaine et action sociale",
      R: "Arts, spectacles et loisirs",
      S: "Autres activités de services",
      T: "Ménages employeurs",
      U: "Activités extraterritoriales",
    },
    commitmentsTitle: "Engagements",
    commitments: {
      mission: "Société à mission",
      ess: "Économie sociale et solidaire",
      inclusive: "Entreprise inclusive",
      ges: "Bilan carbone publié",
      egapro: "Index égalité femmes-hommes",
    },
    yes: "Oui",
    no: "Non",
    egaproScore: "{score}/100 en {year}",
    egaproMissing: "Non déclaré",
    employerPageTitle: "Page employeur France Travail",
    employerPageLink: "Voir sa page employeur",
    employerPageOffers: "{count} offres publiées",
    employerPageMissing: "Aucune page employeur connue pour cette entreprise.",
    newTab: "(nouvel onglet)",
    sourcesTitle: "Sources",
    sources: {
      annuaire: "Annuaire des entreprises (API Recherche d'entreprises, État)",
      egapro: "Index de l'égalité professionnelle : ministère du Travail (Egapro)",
      employerPage: "Page employeur : France Travail",
    },
    again: "Vérifier un autre employeur",
  },
  cta: {
    title: "Et les entreprises qui recrutent dans votre métier ?",
    body: "Celles qui embauchent près de chez vous, même sans annonce, avec leur fiche. Créez votre compte : il suffit d'un email.",
    button: "Voir les entreprises qui recrutent",
  },
  lead: {
    body: "Nous vous envoyons un lien de connexion : il ouvre la liste des entreprises qui recrutent.",
    emailLabel: "Votre email",
    emailPlaceholder: "vous@exemple.fr",
    consent:
      "J'accepte de créer un compte CVSpark et de recevoir ce lien de connexion.",
    submit: "Recevoir mon lien",
    submitting: "Envoi…",
    success: "Vérifiez votre boîte mail",
    successBody: "Le lien ouvre la liste des entreprises qui recrutent.",
  },
}
