import type { Metadata } from "next"

import { getDictionary } from "@/lib/dictionaries"
import { defaultLocale, locales, type Locale } from "@/lib/i18n"

const OG_LOCALES: Record<Locale, string> = { fr: "fr_FR", en: "en_US" }

/**
 * The metadata every indexable page needs, beyond its <title>.
 *
 * Next merges `openGraph` and `twitter` shallowly: a page that sets them
 * replaces the layout's whole object. Without this helper each sub-page kept
 * the home page's share title and description, so a shared link to the ATS
 * check announced the home page. For the same reason the image generated by
 * `[locale]/opengraph-image` is named here: a page that sets `openGraph` no
 * longer inherits it.
 */
export function pageMetadata({
  locale,
  title,
  description,
  path,
}: {
  locale: Locale
  title: string
  description: string
  /** The page's path in each language, e.g. `atsPath`. */
  path: (locale: Locale) => string
}): Metadata {
  const image = {
    url: `/${locale}/opengraph-image`,
    width: 1200,
    height: 630,
    alt: getDictionary(locale).meta.ogAlt,
  }

  return {
    description,
    alternates: {
      canonical: path(locale),
      languages: {
        ...Object.fromEntries(locales.map((other) => [other, path(other)])),
        "x-default": path(defaultLocale),
      },
    },
    openGraph: {
      type: "website",
      siteName: "CVSpark",
      locale: OG_LOCALES[locale],
      url: path(locale),
      title,
      description,
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
    },
  }
}
