import type { FtHttpClient } from "../france-travail/ft-http.client";

/** Where France Travail publishes an employer page, checked live on 2026-09-24. */
export const EMPLOYER_PAGE_URL = "https://recrute.francetravail.fr/page-employeur";

export interface EmployerPage {
  /** The active `urlPath`, e.g. `helpline-913`. */
  path: string;
  offers: number;
  /** Written by the employer, rather than generated by France Travail. */
  edited: boolean;
}

/** One result of `/page-employeur/recherche`, trimmed to the fields read. */
interface EmployerPageResult {
  pageEmployeur?: {
    sirenOrSiret?: string;
    offresCount?: number;
    statutWrapper?: { auto?: boolean };
    urls?: Array<{ urlPath?: string; actif?: boolean }>;
    employeur?: { etablissements?: Array<{ siret?: string }> };
  };
}

interface EmployerPageSearch {
  pageEmployeurResults?: EmployerPageResult[];
}

/**
 * France Travail's Synthèse Pages employeurs (US-116). Its only resource is a
 * search: `where`, a department, is required and `what` searches names and
 * taglines, while `siret` is accepted and ignored. So a company is looked up
 * by name where it has an establishment, then recognised by its SIREN.
 */
export class EmployerPagesSource {
  constructor(
    private readonly franceTravail: Pick<FtHttpClient, "isEnabled" | "request">,
  ) {}

  isAvailable(): boolean {
    return this.franceTravail.isEnabled("pages-employeurs");
  }

  /** The company's page, `null` when it has none, `undefined` when the API failed. */
  async find(
    siren: string,
    names: readonly string[],
    department: string,
  ): Promise<EmployerPage | null | undefined> {
    if (!department) return null;

    for (const what of [...new Set(names.map((name) => name.trim()))].filter(Boolean)) {
      const result = await this.franceTravail.request<EmployerPageSearch>(
        "pages-employeurs",
        {
          body: { pageMaxSize: 10, pageNumber: 1, what, where: department },
          method: "POST",
          path: "/page-employeur/recherche",
        },
      );

      if (result.kind === "unavailable") return undefined;
      if (result.kind === "empty") continue;

      const page = readEmployerPage(siren, result.data.pageEmployeurResults);
      if (page) return page;
    }

    return null;
  }
}

/** The result that belongs to `siren`, by its own SIREN or one of its establishments. */
export function readEmployerPage(
  siren: string,
  results: readonly EmployerPageResult[] | undefined,
): EmployerPage | null {
  const page = results
    ?.map((result) => result.pageEmployeur)
    .find(
      (candidate) =>
        candidate?.sirenOrSiret?.slice(0, 9) === siren ||
        candidate?.employeur?.etablissements?.some((establishment) =>
          establishment.siret?.startsWith(siren),
        ),
    );
  const path = page?.urls?.find((url) => url.actif)?.urlPath;
  if (!page || !path) return null;

  return {
    edited: page.statutWrapper?.auto === false,
    offers: page.offresCount ?? 0,
    path,
  };
}
